services:
  # 1. Deepfake Dashboard Oversight (Free Version)
  - type: web
    name: deep-dash-purnendu
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn member5_dashboard_oversight.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: SECRET_KEY
        generateValue: true

  # 2. Dummy Social Platform (Free Version)
  - type: web
    name: social-purnendu
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn dummy_social_platform.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: SECRET_KEY
        generateValue: true

  # 3. Public Reporting System (Free Version)
  - type: web
    name: reporting-purnendu
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn public_reporting_system.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: SECRET_KEY
        generateValue: true
